edition = "2018"
comment_width = 160
condense_wildcard_suffixes = true
max_width = 160
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
overflow_delimited_expr = true

