[package]
name = "counterbot"
version = "0.1.0-dev"
authors = ["Balint BIRO <j.balint.biro@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
nom = "*"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"

